### ISSUE TITLE
Insert License Code

### ISSUE THREAD

**Issue by jonasermert** [justboil/docs#1]
Cannot enter the licence key. I bought "Admin One Vue.js 3.x Tailwind 3.x dashboard template" but can still only use the demo. Nowhere is there an explanation of where to enter it. Please add.

**Comment by vikdiesel** [comment]
Hi, thanks for buying, please check email receipt for download link (the **View content** button)

**Comment by jonasermert** [comment]
Yes, on the page I downloaded the content and copied the licence key. I have followed all the steps in your instructions (https://justboil.github.io/docs/basics/getting-started.html#pre-requisites). It works, but where do I enter the licence code? The app only runs in the demo version!

**Comment by vikdiesel** [comment]
If you see [the premium version demo](https://tailwind-vue.justboil.me/#/), then it's correct. Admin One is a dashboard template.

**Comment by jonasermert** [comment]
Yes, I see this version. Than it's ok. Thank you.
